print("<======Biodata Diri======>")
print("<========================>")
Nama = str(input("Masukkan Nama : "))
NIM = int(input("Masukkan NIM : "))
Prodi = str(input("Prodi anda : "))
Tanggal_Lahir = str(input("TTL : "))
Fisik_T = float(input("Tinggi badan (Cm) :"))
Fisik_B = float(input("Berat badan (Kg): "))
X = [Nama, NIM, Prodi, Tanggal_Lahir, Fisik_T, Fisik_B]
print(X)
print("\nTampilan Data Anda sebagai Berikut")
print("<================================>")
print("Nama         :", X[0])
print("NIM          :", X[1])
print("Jurusan      :", X[2])
print("TTL          :", X[3])
print("Tinggi Badan :", X[4])
print("Berat Badan  :", X[5])